-- MySQL Script generated by MySQL Workbench
-- Fri Apr 24 11:04:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;

-- -----------------------------------------------------
-- Table `shop`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`status` ;

CREATE TABLE IF NOT EXISTS `shop`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`));


-- -----------------------------------------------------
-- Table `shop`.`vat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`vat` ;

CREATE TABLE IF NOT EXISTS `shop`.`vat` (
  `id_vat` INT(11) NOT NULL AUTO_INCREMENT,
  `VAT` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_vat`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`address` ;

CREATE TABLE IF NOT EXISTS `shop`.`address` (
  `id_address` INT(11) NOT NULL AUTO_INCREMENT,
  `zipcode` INT(5) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `street` VARCHAR(20) NULL DEFAULT NULL,
  `housenumber` VARCHAR(3) NULL DEFAULT NULL,
  `apartnumber` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_address`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`user` ;

CREATE TABLE IF NOT EXISTS `shop`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `name` VARCHAR(30) NULL,
  `last_name` VARCHAR(30) NULL,
  `phone` INT(9) NULL,
  `id_address` INT(11) NULL,
  `admin` INT(1) NOT NULL,
  `isactive` INT(1) NOT NULL,
  PRIMARY KEY (`id_user`),
  CONSTRAINT `address-user`
    FOREIGN KEY (`id_address`)
    REFERENCES `shop`.`address` (`id_address`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`ship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`ship` ;

CREATE TABLE IF NOT EXISTS `shop`.`ship` (
  `id_ship` INT(11) NOT NULL AUTO_INCREMENT,
  `shipmethod` VARCHAR(20) NULL DEFAULT NULL,
  `ship_price` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_ship`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`orders` ;

CREATE TABLE IF NOT EXISTS `shop`.`orders` (
  `id_order` INT(11) NOT NULL AUTO_INCREMENT,
  `id_user` INT(11) NULL DEFAULT NULL,
  `order_date` DATE NOT NULL,
  `order_Status` INT(2) NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `id_vat` INT(11) NULL DEFAULT NULL,
  `id_ship` INT(10) NOT NULL,
  PRIMARY KEY (`id_order`),
  CONSTRAINT `order-vat`
    FOREIGN KEY (`id_vat`)
    REFERENCES `shop`.`vat` (`id_vat`),
  CONSTRAINT `user-order`
    FOREIGN KEY (`id_user`)
    REFERENCES `shop`.`user` (`id_user`),
  CONSTRAINT `order-ship`
    FOREIGN KEY (`id_ship`)
    REFERENCES `shop`.`ship` (`id_ship`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order-status`
    FOREIGN KEY (`order_Status`)
    REFERENCES `shop`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`categories` ;

CREATE TABLE IF NOT EXISTS `shop`.`categories` (
  `id_category` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_category`)
)
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`products` ;

CREATE TABLE IF NOT EXISTS `shop`.`products` (
  `id_products` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `amount` INT(11) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `description` VARCHAR(20) NULL DEFAULT NULL,
  `id_category` INT(11) NOT NULL,
  `photo1` VARCHAR(45) NOT NULL,
  `photo2` VARCHAR(45) NULL,
  `photo3` VARCHAR(45) NULL,
  `photo4` VARCHAR(45) NULL,
  PRIMARY KEY (`id_products`),
  CONSTRAINT `categories-product`
    FOREIGN KEY (`id_category`)
    REFERENCES `shop`.`categories` (`id_category`))
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_polish_ci;


-- -----------------------------------------------------
-- Table `shop`.`orderProduct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shop`.`orderProduct` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orderProduct` (
  `orderProduct_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT(11) NOT NULL,
  `product_id` INT(11) NOT NULL,
  `qty` INT(2) NOT NULL,
  `finalPrice` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`orderProduct_id`),
  CONSTRAINT `orderProduct - order`
    FOREIGN KEY (`order_id`)
    REFERENCES `shop`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orderProduct - product`
    FOREIGN KEY (`product_id`)
    REFERENCES `shop`.`products` (`id_products`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `shop` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
